name: snowflake_timetravel_table Black Checker

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - '**'

jobs:
  check_black:
    name: Check Black
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Tox
      run: pip install tox
    - name: Run Black
      run: tox -e black
